### ISSUE TITLE
Carpool list needs to display distance

### ISSUE THREAD

**Issue by ianaldrighetti** [FroYoInc/sprinkles#43]
The distance should be returned already, but the carpool list is not showing it.

**Comment by bbuxell** [comment]
There is distance data from the rethink query on the backend that we are not currently returning, but we can potentially.  Is that what this is referring to?

**Comment by ianaldrighetti** [comment]
@bbuxell Yup, so I guess I was wrong. The backend will need to return that, then.

**Comment by ianaldrighetti** [comment]
https://github.com/FroYoInc/wafflecone/issues/46

**Comment by ianaldrighetti** [comment]
I made an issue in wafflecone.
